# makefile for the Locale Kit language files
# for now, we will just copy the files into the correct location

LANGUAGE_DIR=/etc/locale/languages

all:
# do nothing

install:
	copyattr -d *.language $(LANGUAGE_DIR)
